name: CI

on: [push]

jobs:
  windows-mingw:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Init Submodules
      run: git submodule update --init --recursive
    - name: Build
      run: .\build-mingw.ps1
    - name: Install Go
      run: choco install -y golang
    - name: Go Build
      run: go build .\gotest
    - name: Test Go Build
      run: .\gotest.exe
    - name: Upload lib
      uses: actions/upload-artifact@v1.0.0
      with:
        name: windows-mingw-lib
        path: libzt\bin\lib
    - name: Upload include
      uses: actions/upload-artifact@v1.0.0
      with:
        name: windows-mingw-include
        path: libzt\include