name: CI

on: [push]

jobs:
  windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: CMake
      run: cmake -G "MinGW Makefiles" .
    - name: Make
      run: mingw32-make
