name: CI

on: [push]

jobs:
  windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: CMake
      uses: lukka/run-cmake@v0.7
      with:
        cmakeBuildType: MinSizeRel
        cmakeGenerator: MinGW Makefiles
    - name: Make
      run: mingw32-make
