name: CI

on: [push]

jobs:
  windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Init Submodules
      run: git submodule update --init --recursive
    - name: CMake
      run: cmake -G "MSYS Makefiles" libzt
    - name: Make
      run: make
